### ISSUE TITLE
Design and add a logo for the webextension icon in the browser toolbar 

### ISSUE THREAD

**Issue by ritiksoni00** [HakinCodes/extension-activity-logger#5]

**Comment by Ajitesh13** [comment]
Yes we want a logo for the webextension

**Comment by ritiksoni00** [comment]
Ohkay! no worry, ill cover that, you can tell me some basic idea about it or raw design so that I can have an idea

**Comment by ritiksoni00** [comment]
And you should put it on the Easy category cause it takes time too...

**Comment by Ajitesh13** [comment]
Ok I will put it in the easy category because this issue contain "Design and add". So you also have to add this issue in the specific location to make it appear on the browser toolbar. Dont spend do much time in the designing part. Your creativity should speak, but it should show the function of this web-extension and that is "Activity Logging".

**Comment by ritiksoni00** [comment]
sorry for the update but i was stuck ... start working it from tomorrow!

**Comment by BellatrixLestrangee** [comment]
I wish to work on this issue. Can I be assigned? @Ajitesh13

**Comment by ritiksoni00** [comment]
Please Assign Me so that i can see it in my Assigned section! forget about this Issue @Ajitesh13

**Comment by Ajitesh13** [comment]
> I wish to work on this issue. Can I be assigned? @Ajitesh13

@BellatrixLestrangee thanx for taking interest, if you want to work on this, go ahead and submit a PR

**Comment by ritiksoni00** [comment]
Sorry im unable to this

**Comment by Ajitesh13** [comment]
@BellatrixLestrangee You can take this issue now

**Comment by BellatrixLestrangee** [comment]
Alright, on it.
